---
title: "Portfolio 5"
output: 
  html_document: 
    highlight: pygments
    theme: cerulean
---

```{r load_packages}
library(carData)
data(CES11)
```

### The Goal

For my final two portfolio pieces, I am going to switch gears slightly. As we explored both public opinion in the United States, as well as public opinion in Australia, Norway, and Sweden, I feel it is time we turn to one more country, Canada. As a dual citizen of both the United States and Canada, I am always interested in ways to involve Canada into my studies, especially Canadian politics. 

I have come acorss a new data set, CES11, which is drawn from the 2011 Canadian National Election Study. This study surveyed many variables that I will discuss in the next section but specifically asked individuals about their stances on banning abortion. As the previous portfolio pieces revolved around public opinion towards both presidential administrations and government poverty intervention, abortion is another salient issue that much of the population feels rather divided on. 

I believe this data set will produce some interesting findings. For this portfolio piece specifically, my goal is to create a visualization that answers the question: Is Canada divided on the abortion conflict or are there specific regions (provinces) that tend to lean more strongly one way over another. 

### The Data 

The data set, CES11, is derrived from the carData package. There are 2231 observations and 9 variables included in this data frame. Each observation represents one surveyed participant. The 9 variables include ID, province, population, weight, gender, abortion, importance, education, and urban. The descriptions of each variable are listed below. 

ID: Household ID number.

Province: A factor with (alphabetical) levels AB, BC, MB, NB, NL, NS, ON, PE, QC, SK; the sample was stratified by province.

Population: Population of the respondent's province, number over age 17.

Weight: Weight sample to size of population, taking into account unequal sampling probabilities by province and household size.

Gender: A factor with levels Female, Male.

Abortion: Attitude toward abortion, a factor with levels No, Yes; answer to the question "Should abortion be banned?"

Importance: Importance of religion, a factor with (alphabetical) levels not, notvery, somewhat, very; answer to the question, "In your life, would you say that religion is very important, somewhat important, not very important, or not important at all?"

Education: A factor with (alphabetical) levels bachelors (Bachelors degree), college (community college or technical school), higher (graduate degree), HS (high-school graduate), lessHS (less than high-school graduate), somePS (some post-secondary).

Urban: Place of residence, a factor with levels rural, urban.

Before jumping into the main question, I will first 

### The Product

### The interpretation

