<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Portfolio 4</title>

<script src="site_libs/header-attrs-2.30/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    var j = 0;
    while (j < rules.length) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") {
        j++;
        continue;
      }
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') {
        j++;
        continue;
      }
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>







<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Portfolio</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="about.html">About</a>
</li>
<li>
  <a href="p01.html">Portfolio 1</a>
</li>
<li>
  <a href="p02.html">Portfolio 2</a>
</li>
<li>
  <a href="p03.html">Portfolio 3</a>
</li>
<li>
  <a href="p04.html">Portfolio 4</a>
</li>
<li>
  <a href="p05.html">Portfolio 5</a>
</li>
<li>
  <a href="p06.html">Portfolio 6</a>
</li>
<li>
  <a href="p07.html">Portfolio 7</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Portfolio 4</h1>

</div>


<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse) </span>
<span id="cb1-2"><a href="#cb1-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" tabindex="-1"></a><span class="fu">library</span>(carData)</span>
<span id="cb1-4"><a href="#cb1-4" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;WVS&quot;</span>)</span></code></pre></div>
<div id="the-goal" class="section level3">
<h3>The Goal</h3>
<p>With a few portfolio’s under my belt, I want to continue building off
of the WVS data set to explore research questions not yet answered by
the previous two projects. As we have both addressed public opinion of
presidents in the United States, and now public opinion’s of government
action in the United States, I think it is time to branch out to the
other three countries included in the selected data set, WVS.</p>
<p>The goal of this specific portfolio piece is to dive into the three
other countries to investigate whether the United State’s trends in data
are universal or unique. As we are exploring public opinion of
government poverty intervention, I am interested to see how Norway,
Sweden, and Australia differ from that of the United States. The end
result will be a visualization of all countries and how they differ in
poverty response distributions. To assess earlier findings in relation
to both the general trend across all four countries as well as the
demographic variable’s effects on the poverty question, refer to
portfolio pieces 2-3.</p>
</div>
<div id="the-data" class="section level3">
<h3>The Data</h3>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" tabindex="-1"></a><span class="fu">view</span>(WVS)</span>
<span id="cb2-2"><a href="#cb2-2" tabindex="-1"></a><span class="fu">nrow</span>(WVS)</span></code></pre></div>
<pre><code>## [1] 5381</code></pre>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" tabindex="-1"></a><span class="fu">ncol</span>(WVS)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>To bring everyone up to speed, the WVS data set comes from the
carData package. The data was derrived from a survey collected in the
United States, Australia, Norway, and Sweden. The researchers of the
study collected 5381 responses with most coming from Australian and
American participants. Six total variables were assessed in the
survey.</p>
<p>The main variable of interest that the researchers intended to
measure was public opinion of the respective government’s action towards
dealing with poverty in that country. Participants were asked the given
question: “Do you think that what the government is doing for people in
poverty in this country is about the right amount, too much, or too
little?” to which they could respond: “Too Little”, “About Right”, “Too
Much”. Other variables accounted for are described below.</p>
<p>poverty “Do you think that what the government is doing for people in
poverty in this country is about the right amount, too much, or too
little?” (ordered): Too Little, About Right, Too Much</p>
<p>religion Member of a religion: no or yes.</p>
<p>degree Held a university degree: no or yes.</p>
<p>country Australia, Norway, Sweden, or USA.</p>
<p>age in years.</p>
<p>gender male or female.</p>
<p>This is a co-ed sample with almost an even distribution of male and
female participants. Additionally, the data surveys variables such as
having a college degree and being religious. Age is also accounted for
in this data set and will be used in future portfolio pieces.</p>
<div id="portfolio-pieces-2-3-recap" class="section level5">
<h5>Portfolio Pieces 2-3 Recap</h5>
<p>In portfolio piece 2, we explored the demographics and distributions
of participants within the data set. We also created a visualization
depicting the survey’s general distribution of responses to the poverty
question as see below.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" tabindex="-1"></a>WVS <span class="sc">%&gt;%</span></span>
<span id="cb6-2"><a href="#cb6-2" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty)) <span class="sc">+</span></span>
<span id="cb6-3"><a href="#cb6-3" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="p04_files/figure-html/plot-poverty-1.png" alt="" width="672" /></p>
<p>As shown, the general majority of participants believe that their
government is doing too little for the for the poverty issue in their
country. The second most popular response was “just right” which
indicates the particpants felt their government was handling the poverty
issue in their country well.</p>
<p>In portfolio 3, I began to isolate the responses from individuals
within the United States to investigate American public opinion compared
to the general responses. The United States distribution of poverty
question responses are below.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" tabindex="-1"></a>WVS_US <span class="ot">&lt;-</span> WVS <span class="sc">%&gt;%</span></span>
<span id="cb7-2"><a href="#cb7-2" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;USA&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS_US, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty)) <span class="sc">+</span></span>
<span id="cb8-2"><a href="#cb8-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="p04_files/figure-html/unnamed-chunk-3-1.png" alt="" width="672" /></p>
<p>As seen in the bar plot above, the United States does not follow the
same distribution as the general responses do. The second highest
response was “too much”. We also learned from portfolio 3 that age was
the only variable that begins to offer some explanation or effect for
such responses in terms of predicting individual responses.</p>
<p>Now, I am interested to see how other countries compare in this data
set.</p>
</div>
</div>
<div id="the-product" class="section level3">
<h3>The Product</h3>
<p>Firstly, I will explore each country and their distribution of
responses to how their government is handeling the poverty issue.</p>
<div id="australia" class="section level5">
<h5>Australia</h5>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" tabindex="-1"></a>WVS_AU <span class="ot">&lt;-</span> WVS <span class="sc">%&gt;%</span></span>
<span id="cb9-2"><a href="#cb9-2" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Australia&quot;</span>)</span>
<span id="cb9-3"><a href="#cb9-3" tabindex="-1"></a><span class="fu">nrow</span>(WVS_AU)</span></code></pre></div>
<pre><code>## [1] 1874</code></pre>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" tabindex="-1"></a><span class="fu">ncol</span>(WVS_AU)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>This data set contains 1874 responses each representing an Australian
participant.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS_AU, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty)) <span class="sc">+</span></span>
<span id="cb13-2"><a href="#cb13-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="p04_files/figure-html/unnamed-chunk-5-1.png" alt="" width="672" /></p>
<p>The general trend apparent in Norway participant responses to the
poverty question resembles the general distribution of all four
countries. Differing from the United States but on par with average
results, the most common response was that the government was dong “Too
Little” for poverty followed close behind by “about right”.</p>
</div>
<div id="norway" class="section level5">
<h5>Norway</h5>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" tabindex="-1"></a>WVS_NO <span class="ot">&lt;-</span> WVS <span class="sc">%&gt;%</span></span>
<span id="cb14-2"><a href="#cb14-2" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Norway&quot;</span>)</span>
<span id="cb14-3"><a href="#cb14-3" tabindex="-1"></a><span class="fu">nrow</span>(WVS_NO)</span></code></pre></div>
<pre><code>## [1] 1127</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" tabindex="-1"></a><span class="fu">ncol</span>(WVS_NO)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>This data set contains 1127 responses each representing a Norwegion
participant.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS_NO, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty)) <span class="sc">+</span></span>
<span id="cb18-2"><a href="#cb18-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="p04_files/figure-html/unnamed-chunk-7-1.png" alt="" width="672" /></p>
<p>The general trend apparent in Norway participant responses to the
poverty question resembles the general distribution of all four
countries, only slightly more extreme as there are significantly fewer
responses for the “too much” option.</p>
</div>
<div id="sweden" class="section level5">
<h5>Sweden</h5>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" tabindex="-1"></a>WVS_SW <span class="ot">&lt;-</span> WVS <span class="sc">%&gt;%</span></span>
<span id="cb19-2"><a href="#cb19-2" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">&quot;Sweden&quot;</span>)</span>
<span id="cb19-3"><a href="#cb19-3" tabindex="-1"></a><span class="fu">nrow</span>(WVS_SW)</span></code></pre></div>
<pre><code>## [1] 1003</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" tabindex="-1"></a><span class="fu">ncol</span>(WVS_SW)</span></code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>This data set contains 1003 responses each representing a Swedish
participant.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS_SW, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty)) <span class="sc">+</span></span>
<span id="cb23-2"><a href="#cb23-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>()</span></code></pre></div>
<p><img src="p04_files/figure-html/unnamed-chunk-9-1.png" alt="" width="672" />
The general trend apparent in Swedish participant responses to the
poverty question resembles the general distribution of all four
countries, only slightly more extreme as there are significantly fewer
responses for the “too much” option.</p>
<p>Finally, I would like to build a visualization of the average
responses, faceted by country so that we can interpret trends in data
and patterns among different countries. I will add cosmetic design to
enhance the visual.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="at">data =</span> WVS, <span class="at">mapping =</span> <span class="fu">aes</span>(<span class="at">x =</span> poverty, <span class="at">fill =</span> country)) <span class="sc">+</span></span>
<span id="cb24-2"><a href="#cb24-2" tabindex="-1"></a>  <span class="fu">geom_bar</span>() <span class="sc">+</span></span>
<span id="cb24-3"><a href="#cb24-3" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Public Opinion of Government Poverty Intervention&quot;</span>, </span>
<span id="cb24-4"><a href="#cb24-4" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">&quot;Faceted by Country&quot;</span>)</span></code></pre></div>
<p><img src="p04_files/figure-html/unnamed-chunk-10-1.png" alt="" width="672" /></p>
</div>
</div>
<div id="the-interpretation" class="section level3">
<h3>The Interpretation</h3>
<p>The United States appears to stand alone in its distribution as most
people respond with the two extremes of the poverty question responses.
Most Americans seem to think that the government is either doing “too
much” or “too little” on the poverty issue with the fewest participants
answering “about right”. This differs from Australia, Norway, and Sweden
as their response distributions follow that of the average responses
among all four countries. Although, Norway and Sweden stand slightly
separate as they have the fewest responses within the “too much”
category, most likely aiding in the average distribution as the United
States responses diverge from the common distribution.</p>
<p>Norway, Sweden, and Australia all share the similar distribution with
very few participants responding that their government is doing “too
much”. On the other hand, the United States’ second most common response
is this option in itself. It would be interesting to investigate some of
the policy relating to poverty taking place in these countries to see
whether public opinion reflects such advancements, or lack there of.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
